# https://travis-ci.org/Hrabal/ClassCLI
sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "3.5"
  - "3.6"
install:
  - "pip3 install coveralls"
  - "pip3 install -r requirements.txt"
branches:
  only:
    - master
# command to run tests
script: coverage run -m unittest discover
after_success:
  coveralls
after_script:
  - sleep 3 # helps travis finish logging